name: Deploy Stage

on:
  workflow_call:

concurrency:
  group: prod-environment
  cancel-in-progress: false

permissions:
  actions: read
  id-token: write
  contents: read

jobs:
  deploy-infra:
    name: Deploy Infra
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy more infra
        run: flibby 'Deploy more infra'
